# Generated by Django 5.0 on 2023-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_pokedexuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="trainer_qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="trainer_qr_codes/"
            ),
        ),
    ]
