# Generated by Django 5.0 on 2023-12-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_pokedexuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="date_of_birth",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.IntegerField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/pikachu-placeholder.webp",
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="trainer_qr_code",
            field=models.ImageField(
                blank=True,
                default="static/images/trainer-qr-code.webp",
                upload_to="trainer_qr_codes/",
            ),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
