# Generated by Django 5.0 on 2023-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_pokedexuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
