# Generated by Django 5.0 on 2023-12-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_pokedexuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, default="1234 1234 1234", max_length=20),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/pikachu-placeholder.webp",
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="trainer_qr_code",
            field=models.ImageField(
                blank=True,
                default="static/images/trainer-qr-code.webp",
                upload_to="trainer_qr_codes/",
            ),
        ),
    ]
