# Generated by Django 5.0 on 2023-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_pokedexuser_bio_alter_pokedexuser_go_trainer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
