# Generated by Django 5.0 on 2023-12-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_pokedexuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
