# Generated by Django 5.0 on 2023-12-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_pokedexuser_go_trainer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, default="123412341234", max_length=20),
        ),
    ]
