# Generated by Django 5.0 on 2023-12-30 00:11

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_pokedexuser_go_trainer_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pokedexuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="bio",
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, default="123412341234", max_length=20),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
