# Generated by Django 5.0 on 2023-12-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_pokedexuser_managers_alter_pokedexuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, default=None),
        ),
    ]
