# Generated by Django 5.0 on 2023-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_pokedexuser_go_trainer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="pokedexuser",
            name="trainer_qr_code",
            field=models.ImageField(
                blank=True, default=None, upload_to="trainer_qr_codes/"
            ),
        ),
    ]
