# Generated by Django 5.0 on 2023-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_pokedexuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexuser",
            name="go_trainer_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
