# Generated by Django 5.0 on 2023-12-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokedex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")], default=0
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("numbers_of_pokemon", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserPokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon_id", models.IntegerField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "pokedex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokedex.pokedex",
                    ),
                ),
            ],
            options={
                "unique_together": {("pokemon_id", "pokedex")},
            },
        ),
    ]
