# Generated by Django 5.0 on 2023-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0002_pokedex_name_pokedex_user_alter_pokedex_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokedex",
            name="status",
        ),
        migrations.AddField(
            model_name="pokedex",
            name="color",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="pokedex",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
