# Generated by Django 5.0 on 2023-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0003_remove_pokedex_status_pokedex_color_alter_pokedex_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedex",
            name="color",
            field=models.CharField(max_length=7),
        ),
    ]
