# Generated by Django 5.0 on 2023-12-20 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0006_userpokemon_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpokemon",
            name="additional_notes",
        ),
    ]
