# Generated by Django 5.0 on 2023-12-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0007_remove_userpokemon_additional_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokedex",
            name="is_public",
        ),
        migrations.AddField(
            model_name="userpokemon",
            name="pokemon_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
