# Generated by Django 5.0 on 2023-12-21 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0008_remove_pokedex_is_public_userpokemon_pokemon_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokedex",
            name="numbers_of_pokemon",
        ),
    ]
