# Generated by Django 5.0 on 2023-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0009_remove_pokedex_numbers_of_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpokemon",
            name="pokemon_name",
            field=models.CharField(default="Unknown Pokemon.", max_length=100),
        ),
    ]
