# Generated by Django 5.0 on 2023-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0010_alter_userpokemon_pokemon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedex",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="images/pokedex-cover.webp",
                null=True,
                upload_to="pokedex_covers/",
            ),
        ),
    ]
